enum GatheringDiscipline { mining, woodcutting, fishing }

extension GatheringDisciplineDetails on GatheringDiscipline {
  String get skillId => switch (this) {
    GatheringDiscipline.mining => 'mining',
    GatheringDiscipline.woodcutting => 'woodcutting',
    GatheringDiscipline.fishing => 'fishing',
  };

  String get displayName => switch (this) {
    GatheringDiscipline.mining => 'Mineração',
    GatheringDiscipline.woodcutting => 'Corte de madeira',
    GatheringDiscipline.fishing => 'Pesca',
  };
}

enum GatheringRarity { common, uncommon, rare, epic, legendary, magical }

class GatheringResource {
  final String id;
  final GatheringDiscipline discipline;
  final String name;
  final int requiredLevel;
  final int cycleSeconds;
  final double experiencePerCycle;
  final int baseQuantity;
  final GatheringRarity rarity;
  final String description;

  const GatheringResource({
    required this.id,
    required this.discipline,
    required this.name,
    required this.requiredLevel,
    required this.cycleSeconds,
    required this.experiencePerCycle,
    required this.baseQuantity,
    required this.rarity,
    required this.description,
  });

  static const List<GatheringResource> all = [
    GatheringResource(
      id: 'copper',
      discipline: GatheringDiscipline.mining,
      name: 'Minério de cobre',
      requiredLevel: 1,
      cycleSeconds: 3,
      experiencePerCycle: 5.6,
      baseQuantity: 1,
      rarity: GatheringRarity.common,
      description: 'Minério básico, estável e ideal para começar.',
    ),
    GatheringResource(
      id: 'coal',
      discipline: GatheringDiscipline.mining,
      name: 'Carvão mineral',
      requiredLevel: 5,
      cycleSeconds: 4,
      experiencePerCycle: 6.8,
      baseQuantity: 1,
      rarity: GatheringRarity.common,
      description: 'Combustível escuro que mantém acesas as forjas do reino.',
    ),
    GatheringResource(
      id: 'rune_essence',
      discipline: GatheringDiscipline.mining,
      name: 'Essência rúnica',
      requiredLevel: 10,
      cycleSeconds: 1,
      experiencePerCycle: 1.3,
      baseQuantity: 1,
      rarity: GatheringRarity.magical,
      description: 'Reagente mineral usado para fabricar magias.',
    ),
    GatheringResource(
      id: 'iron',
      discipline: GatheringDiscipline.mining,
      name: 'Minério de ferro',
      requiredLevel: 20,
      cycleSeconds: 5,
      experiencePerCycle: 15,
      baseQuantity: 1,
      rarity: GatheringRarity.uncommon,
      description: 'Metal resistente para ferramentas de qualidade.',
    ),
    GatheringResource(
      id: 'silver',
      discipline: GatheringDiscipline.mining,
      name: 'Minério de prata',
      requiredLevel: 30,
      cycleSeconds: 7,
      experiencePerCycle: 22.5,
      baseQuantity: 1,
      rarity: GatheringRarity.uncommon,
      description: 'Metal valioso para criações avançadas.',
    ),
    GatheringResource(
      id: 'gold',
      discipline: GatheringDiscipline.mining,
      name: 'Minério de ouro',
      requiredLevel: 40,
      cycleSeconds: 9,
      experiencePerCycle: 31.5,
      baseQuantity: 1,
      rarity: GatheringRarity.rare,
      description: 'Um minério precioso e muito procurado.',
    ),
    GatheringResource(
      id: 'platinum',
      discipline: GatheringDiscipline.mining,
      name: 'Minério de platina',
      requiredLevel: 50,
      cycleSeconds: 12,
      experiencePerCycle: 47.3,
      baseQuantity: 1,
      rarity: GatheringRarity.rare,
      description: 'Metal raro de alto valor.',
    ),
    GatheringResource(
      id: 'mithril',
      discipline: GatheringDiscipline.mining,
      name: 'Minério de mitril',
      requiredLevel: 60,
      cycleSeconds: 15,
      experiencePerCycle: 63.1,
      baseQuantity: 1,
      rarity: GatheringRarity.epic,
      description: 'Metal leve, lendário e extremamente resistente.',
    ),
    GatheringResource(
      id: 'adamantite',
      discipline: GatheringDiscipline.mining,
      name: 'Minério de adamantita',
      requiredLevel: 70,
      cycleSeconds: 19,
      experiencePerCycle: 88.4,
      baseQuantity: 1,
      rarity: GatheringRarity.epic,
      description: 'Um dos metais mais fortes conhecidos.',
    ),
    GatheringResource(
      id: 'runite',
      discipline: GatheringDiscipline.mining,
      name: 'Minério de runita',
      requiredLevel: 80,
      cycleSeconds: 24,
      experiencePerCycle: 111.7,
      baseQuantity: 1,
      rarity: GatheringRarity.legendary,
      description: 'Minério coberto por runas antigas.',
    ),
    GatheringResource(
      id: 'orichalcum',
      discipline: GatheringDiscipline.mining,
      name: 'Minério de oricalco',
      requiredLevel: 90,
      cycleSeconds: 30,
      experiencePerCycle: 146.1,
      baseQuantity: 1,
      rarity: GatheringRarity.legendary,
      description: 'Metal ancestral de poder imenso.',
    ),
    GatheringResource(
      id: 'arcane_crystal',
      discipline: GatheringDiscipline.mining,
      name: 'Cristal arcano',
      requiredLevel: 100,
      cycleSeconds: 38,
      experiencePerCycle: 191.1,
      baseQuantity: 1,
      rarity: GatheringRarity.magical,
      description: 'Cristal essencial para feitiços poderosos.',
    ),
    GatheringResource(
      id: 'essence_stone',
      discipline: GatheringDiscipline.mining,
      name: 'Pedra de essência',
      requiredLevel: 110,
      cycleSeconds: 48,
      experiencePerCycle: 250,
      baseQuantity: 1,
      rarity: GatheringRarity.magical,
      description: 'Concentra energia mágica em estado puro.',
    ),
    GatheringResource(
      id: 'normal_log',
      discipline: GatheringDiscipline.woodcutting,
      name: 'Tronco comum',
      requiredLevel: 1,
      cycleSeconds: 3,
      experiencePerCycle: 10,
      baseQuantity: 1,
      rarity: GatheringRarity.common,
      description: 'Madeira simples encontrada em todo o reino.',
    ),
    GatheringResource(
      id: 'oak_log',
      discipline: GatheringDiscipline.woodcutting,
      name: 'Tronco de carvalho',
      requiredLevel: 5,
      cycleSeconds: 4,
      experiencePerCycle: 15,
      baseQuantity: 1,
      rarity: GatheringRarity.common,
      description: 'Madeira firme para construções básicas.',
    ),
    GatheringResource(
      id: 'willow_log',
      discipline: GatheringDiscipline.woodcutting,
      name: 'Tronco de salgueiro',
      requiredLevel: 10,
      cycleSeconds: 5,
      experiencePerCycle: 25,
      baseQuantity: 1,
      rarity: GatheringRarity.uncommon,
      description: 'Madeira flexível e fácil de trabalhar.',
    ),
    GatheringResource(
      id: 'maple_log',
      discipline: GatheringDiscipline.woodcutting,
      name: 'Tronco de bordo',
      requiredLevel: 15,
      cycleSeconds: 6,
      experiencePerCycle: 35,
      baseQuantity: 1,
      rarity: GatheringRarity.uncommon,
      description: 'Madeira densa com veios marcantes.',
    ),
    GatheringResource(
      id: 'mahogany_log',
      discipline: GatheringDiscipline.woodcutting,
      name: 'Tronco de mogno',
      requiredLevel: 20,
      cycleSeconds: 8,
      experiencePerCycle: 50,
      baseQuantity: 1,
      rarity: GatheringRarity.rare,
      description: 'Madeira nobre usada por artesãos experientes.',
    ),
    GatheringResource(
      id: 'yew_log',
      discipline: GatheringDiscipline.woodcutting,
      name: 'Tronco de teixo',
      requiredLevel: 30,
      cycleSeconds: 10,
      experiencePerCycle: 80,
      baseQuantity: 1,
      rarity: GatheringRarity.rare,
      description: 'Madeira rara, resistente e muito valorizada.',
    ),
    GatheringResource(
      id: 'magic_log',
      discipline: GatheringDiscipline.woodcutting,
      name: 'Tronco mágico',
      requiredLevel: 40,
      cycleSeconds: 14,
      experiencePerCycle: 140,
      baseQuantity: 1,
      rarity: GatheringRarity.epic,
      description: 'Pulsa com a magia antiga da floresta.',
    ),
    GatheringResource(
      id: 'ancient_log',
      discipline: GatheringDiscipline.woodcutting,
      name: 'Tronco ancestral',
      requiredLevel: 50,
      cycleSeconds: 20,
      experiencePerCycle: 250,
      baseQuantity: 1,
      rarity: GatheringRarity.legendary,
      description: 'Retirado de árvores anteriores aos reinos atuais.',
    ),
    GatheringResource(
      id: 'shrimp',
      discipline: GatheringDiscipline.fishing,
      name: 'Camarão',
      requiredLevel: 1,
      cycleSeconds: 3,
      experiencePerCycle: 10,
      baseQuantity: 1,
      rarity: GatheringRarity.common,
      description: 'Uma captura pequena das marés turvas do reino.',
    ),
    GatheringResource(
      id: 'sardine',
      discipline: GatheringDiscipline.fishing,
      name: 'Sardinha',
      requiredLevel: 10,
      cycleSeconds: 4,
      experiencePerCycle: 14,
      baseQuantity: 1,
      rarity: GatheringRarity.common,
      description: 'Cardumes prateados rondam píeres de madeira enegrecida.',
    ),
    GatheringResource(
      id: 'trout',
      discipline: GatheringDiscipline.fishing,
      name: 'Truta',
      requiredLevel: 20,
      cycleSeconds: 5,
      experiencePerCycle: 18.5,
      baseQuantity: 1,
      rarity: GatheringRarity.uncommon,
      description: 'Habita rios gelados que atravessam ruínas esquecidas.',
    ),
    GatheringResource(
      id: 'salmon',
      discipline: GatheringDiscipline.fishing,
      name: 'Salmão',
      requiredLevel: 30,
      cycleSeconds: 7,
      experiencePerCycle: 27.3,
      baseQuantity: 1,
      rarity: GatheringRarity.uncommon,
      description: 'Nada contra correntes avermelhadas sob pontes antigas.',
    ),
    GatheringResource(
      id: 'tuna',
      discipline: GatheringDiscipline.fishing,
      name: 'Atum',
      requiredLevel: 40,
      cycleSeconds: 9,
      experiencePerCycle: 36.9,
      baseQuantity: 1,
      rarity: GatheringRarity.rare,
      description: 'Peixe veloz das águas profundas e sem luar.',
    ),
    GatheringResource(
      id: 'lobster',
      discipline: GatheringDiscipline.fishing,
      name: 'Lagosta',
      requiredLevel: 50,
      cycleSeconds: 12,
      experiencePerCycle: 51.6,
      baseQuantity: 1,
      rarity: GatheringRarity.rare,
      description: 'Oculta-se em covas rochosas sob fortalezas costeiras.',
    ),
    GatheringResource(
      id: 'swordfish',
      discipline: GatheringDiscipline.fishing,
      name: 'Peixe-espada',
      requiredLevel: 60,
      cycleSeconds: 16,
      experiencePerCycle: 72,
      baseQuantity: 1,
      rarity: GatheringRarity.epic,
      description: 'Sua lâmina natural já perfurou muitos cascos de guerra.',
    ),
    GatheringResource(
      id: 'shark',
      discipline: GatheringDiscipline.fishing,
      name: 'Tubarão',
      requiredLevel: 70,
      cycleSeconds: 21,
      experiencePerCycle: 98.7,
      baseQuantity: 1,
      rarity: GatheringRarity.legendary,
      description: 'Predador marcado pelas batalhas dos mares mortos.',
    ),
    GatheringResource(
      id: 'abyssal_eel',
      discipline: GatheringDiscipline.fishing,
      name: 'Enguia abissal',
      requiredLevel: 80,
      cycleSeconds: 27,
      experiencePerCycle: 132.3,
      baseQuantity: 1,
      rarity: GatheringRarity.legendary,
      description: 'Serpente marinha que cintila nas fendas do abismo.',
    ),
    GatheringResource(
      id: 'runic_leviathan',
      discipline: GatheringDiscipline.fishing,
      name: 'Leviatã rúnico',
      requiredLevel: 90,
      cycleSeconds: 34,
      experiencePerCycle: 173.4,
      baseQuantity: 1,
      rarity: GatheringRarity.magical,
      description: 'Colosso ancestral com runas vivas gravadas nas escamas.',
    ),
  ];

  static GatheringResource? byId(String id) {
    for (final resource in all) {
      if (resource.id == id) return resource;
    }
    return null;
  }

  static List<GatheringResource> forDiscipline(GatheringDiscipline discipline) {
    return all.where((resource) => resource.discipline == discipline).toList();
  }
}
